spring:
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: devtestshiv@gmail.com
    password: emndaoipcphypzrm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
